### ISSUE TITLE
pygame.error: video system not initialized

### ISSUE THREAD

**Issue by andrewtheshiny** [nomachinez/pidisplay#1]
It won't run  and gives the following error. Any hints? 

pi@raspberrypi:~ $ python3 pidisplay/pidisplay.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/pi/pidisplay/pidisplay.py", line 257, in <module>
    main()
  File "/home/pi/pidisplay/pidisplay.py", line 23, in main
    pygame.event.set_allowed([pygame.QUIT, pygame.KEYDOWN])
pygame.error: video system not initialized

**Comment by nomachinez** [comment]
Are you running it from ssh?  You must run it from the console.

**Comment by andrewtheshiny** [comment]
Ah. I'll try it from the console.  Do I need X running or not?

Thanks for the fast response.

**Comment by nomachinez** [comment]
No, you do not need X running; PiDisplay will draw its own UI.

**Comment by andrewtheshiny** [comment]
That worked. Thanks.
